name: mikehandcock
favicon: null
layout_spectrum: 0.34512426308356225
typography_spectrum: 0.7529803174547851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2425584385637194
  lightness: 0.45056570507586
  saturation: 0.6910011260770261
  rhythmicContrast: 0.7505151128862053
purpose: []
